"""Added start and end pos to Note

Revision ID: 35f453946f1e
Revises: 85028f013e6d
Create Date: 2024-12-01 11:46:44.985313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import bookworm

# revision identifiers, used by Alembic.
revision: str = '35f453946f1e'
down_revision: Union[str, None] = '85028f013e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('start_pos', sa.Integer(), nullable=True))
    op.add_column('note', sa.Column('end_pos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'end_pos')
    op.drop_column('note', 'start_pos')
    # ### end Alembic commands ###
