"""add_content_hash_column

Revision ID: 707543f03b6d
Revises: 52e39c4f7494
Create Date: 2025-11-12 19:24:24.038832

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "707543f03b6d"
down_revision: str | None = "52e39c4f7494"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("book", sa.Column("content_hash", sa.TEXT(), nullable=True))
    op.add_column(
        "pinned_document", sa.Column("content_hash", sa.TEXT(), nullable=True)
    )
    op.add_column(
        "recent_document", sa.Column("content_hash", sa.TEXT(), nullable=True)
    )
    op.add_column(
        "document_position_info", sa.Column("content_hash", sa.TEXT(), nullable=True)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recent_document", "content_hash")
    op.drop_column("pinned_document", "content_hash")
    op.drop_column("book", "content_hash")
    op.drop_column("document_position_info", "content_hash")
    # ### end Alembic commands ###
