"""add_content_hash_column

Revision ID: 707543f03b6d
Revises: 52e39c4f7494
Create Date: 2025-11-12 19:24:24.038832

"""

from typing import Sequence, Union

from alembic import op
from blake3 import blake3
import sqlalchemy as sa
from sqlalchemy import orm
import bookworm
from bookworm.database import Book, DocumentPositionInfo, RecentDocument, PinnedDocument
from bookworm.document import create_document
from bookworm.document.uri import DocumentUri


# revision identifiers, used by Alembic.
revision: str = "707543f03b6d"
down_revision: Union[str, None] = "52e39c4f7494"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def update_content_hashes(session, model):
    for doc in session.query(model):
        if doc.content_hash:
            continue

        try:
            document = create_document(doc.uri)
            doc.content_hash = document.get_content_hash()
            session.add(doc)
        except Exception as e:
            # Use ascii() to prevent UnicodeEncodeError on Windows GBK consoles
            print(f"Failed to apply content hash to {ascii(doc.title)}: {ascii(e)}")
            continue
    session.commit()


def upgrade() -> None:
    op.add_column("book", sa.Column("content_hash", sa.TEXT(), nullable=True))
    op.add_column(
        "pinned_document", sa.Column("content_hash", sa.TEXT(), nullable=True)
    )
    op.add_column(
        "recent_document", sa.Column("content_hash", sa.TEXT(), nullable=True)
    )
    op.add_column(
        "document_position_info", sa.Column("content_hash", sa.TEXT(), nullable=True)
    )

    bind = op.get_bind()
    session = orm.Session(bind)
    update_content_hashes(session, Book)
    update_content_hashes(session, DocumentPositionInfo)
    update_content_hashes(session, PinnedDocument)
    update_content_hashes(session, RecentDocument)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recent_document", "content_hash")
    op.drop_column("pinned_document", "content_hash")
    op.drop_column("book", "content_hash")
    op.drop_column("document_position_info", "content_hash")
    # ### end Alembic commands ###
