# ----------------------------------------------------------------------
# This file was generated by scripts\make_icons.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

bookmark = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAEBJ"
    b"REFUSIljYBgFAw0YiVDznxJzmIh3C3lg1IJRC0YtGLWARhYQU0CSbQEjGk1VC9ANJckn+ACh"
    b"+oCY+mIU4AYAsN8DI5tBLbIAAAAASUVORK5CYII="
)

# ----------------------------------------------------------------------
fastforward = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAG9J"
    b"REFUSIntktEKwCAIRXXsQ/dHY1/cXgxis+sVegk8EEUcMy2RotiKZoN1KRQEqcwZXeTJQR6C"
    b"gJWjBGGw497fTdQij+5Hrv4WZIIsemYDbKYriN5gDIC/xXiQ15xxJVwX1CLmxqHnJVhycFGs"
    b"4wVAQxqLjOiy7AAAAABJRU5ErkJggg=="
)

# ----------------------------------------------------------------------
general = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAKVJ"
    b"REFUSIntVdsNgDAIpMZFncCRHMkZnAQ/fKShB73aL42XNDYF7hD6EPnxBug51sB2jS4BFZGl"
    b"lTwR5F6MgrUCQ0CMCGoJFYl5AggRuTpzGSvOLYBx9g88crtOJ+GVaJOjJHlZ1HwjpGKSBaNa"
    b"R6Rh41ua3EzeK0BtWSswAZ+o8XNvFuxucXnYw2P9IxslwBBQImyTUSKPmsySIxt7Ed54/IB8"
    b"Czs+kigsyQZLoAAAAABJRU5ErkJggg=="
)

# ----------------------------------------------------------------------
goto = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAHFJ"
    b"REFUSIljYBgFuMF/WhiqADUYbjgLlQzG6VpKLSAYDIw0MhhuLik+ICvSiPEBqQajmInPB1RJ"
    b"Zug+oNRQjBAhN5IZGLA7BsM8JgosIApQ0wKsoTFkfIAzLoeED/CmxEHvg49UcQUOQFSup3kQ"
    b"DX0AACkwDTN+6Dx0AAAAAElFTkSuQmCC"
)

# ----------------------------------------------------------------------
note = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAIVJ"
    b"REFUSIntVVsOgCAMQ+P9r6Bn9ALw7VxZ90jkwyb7gdF2I4zWfnyNrZCra7w7SLTimpBTTqyQ"
    b"+Tfa11rUwToyI/E4q7WIhUmeEaDIowI0eUTAIj8ZZXTJjPPXWbYCV1siAiFyVkC6d42Xw5Eb"
    b"mluMQGogZl7yGgKoRa7xO0N1BZUf2CIY2ZYmQz6GLV8AAAAASUVORK5CYII="
)

# ----------------------------------------------------------------------
open = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAGpJ"
    b"REFUSIntlEEKwCAMBHdLP9yn9kXrRcRLGqhJSsG5BjJxowKbryFJWUVJXBUcjt2UhwgiJI8R"
    b"vWWO1j3BKqdlThEAMYudSY9oCCRlLPweTTMEklgXUcL0V+8b/9C6gEDlLfqVoPQv2rg0Z7wm"
    b"Zh/t7ocAAAAASUVORK5CYII="
)

# ----------------------------------------------------------------------
pause = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAD1J"
    b"REFUSIljZGSgLWCisfmjFhAGLPgk/zMw/IexGRkYMNIDsjwuNUM/iEYtGLVg1IJRCwaDBYyj"
    b"dfKAWwAADk8EM9zga9QAAAAASUVORK5CYII="
)

# ----------------------------------------------------------------------
play = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAGJJ"
    b"REFUSIljYBgFo4DW4D8Ukw2YSLColxwLGIkwmFQ9FFtAkkXEBhGplhPtCmIjGKc5lPgA3SHh"
    b"2CRYqGQBTh9QagHBiKYkiIhKReT4gKR8QIoP+kg1nIGBeB+QbPAoGEEAAAQ5CZEse8hoAAAA"
    b"AElFTkSuQmCC"
)

# ----------------------------------------------------------------------
profile = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAGBJ"
    b"REFUSIntk8EKACAIQ60v78/rGlQ2MzGhnfUNHSP68lYSzNaTfdRgBocYiAEH33IysKxS/BeZ"
    b"X2CewTMhEx0WLf6L3DNAOsCyVgYSMMucGWjgA9cqgzI4dbpxwYodUA1YZguafFuIXgAAAABJ"
    b"RU5ErkJggg=="
)

# ----------------------------------------------------------------------
reading = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAEtJ"
    b"REFUSIntkjEKADAIA03p/7+cLk624uKS4o0iBnIC5gC0bkis9qMB/YB9TUg89nIKdz9W1Pyu"
    b"ApIzvIlxUKLvYCSX6EvWd6AfcACReRNF2fi7JQAAAABJRU5ErkJggg=="
)

# ----------------------------------------------------------------------
rewind = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAG5J"
    b"REFUSIntk7sNwDAIRCHKoN4oykbZzGlcRIgjB6XFk+juY2NZpGm2Y66hdWciuKT7K2CDofYA"
    b"4isRHq7Nu0F5HR5aCM6g3xWpKQyNbIP3BioiN1lCFyEmGMtAOvYENhT5WF1YlPrJFZ6qsdmU"
    b"F2OmIT+XzdTeAAAAAElFTkSuQmCC"
)

# ----------------------------------------------------------------------
search = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAIBJ"
    b"REFUSIntlMEKgDAMQzt/3E/1U+bFwxhdEtaAlwU8SGpex2ojjv5WI34vfg8LWLgEWZlZeBM8"
    b"yZgD1CbSumtFJuHMkwFlIYDUYQVgEQKoY7oNsIgB0ClGb3lfGWAu7t9zR8QzvEuNOFYFzKuM"
    b"qbIFLLMOd5Njiiw/pKLs8o+4XsYcFHbaclE3AAAAAElFTkSuQmCC"
)

# ----------------------------------------------------------------------
settings = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAIRJ"
    b"REFUSIljYBgFAw0YSVT/n1S9TCQYSJY6fK4g1nC85uGygBzDsZpJcx/gi4OPWDSjY9JtRALE"
    b"phi86lgIaCAVwPTCLSKUTMkFDTAGNq9j8wGpiQGuHlsQwSRpnooOIrFxWUbQEaM5Ga/hxAB0"
    b"S/4jYaIcQ/P6gBzwn4GBoYBWhg8+AABLnBu4wHooZgAAAABJRU5ErkJggg=="
)

# ----------------------------------------------------------------------
speech = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAJ5J"
    b"REFUSInllNENwyAMRJ+jLtANukI2bialX6jEMQRTp0qUk1A+gHe2TwSuLglkJYs7BYEz/KnN"
    b"RjpIjT0pzgjAowKQHVALDrBkju7AC60ZZJZYGUQGvwr5l+q7DA5RaRA6GssgK3RU2kDUd1QJ"
    b"mHtBno42D60nZF2EFEvr5SwIgDff/03rsnlmZESufP76Dk5hsHgN9uZphXqzDA7XB1raG2Tu"
    b"/or+AAAAAElFTkSuQmCC"
)

# ----------------------------------------------------------------------
view_image = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAIBJ"
    b"REFUSIntk8ENgCAMRZ9O7AaOgiO4ihPgCk6AJxNoaApRLqYv4VJ+P+lPAcf5FSuQshNamqYG"
    b"TXrjYz2Qm9e01j1zp3kUmtz0ic4kUGb9NEXFQGoLjTV2rtPi0PRAPaKjUgO4hOmp6JrYqI9s"
    b"1XZpNHyLhv+DHuSmLF+YOo7NDR0VLsvgEdmEAAAAAElFTkSuQmCC"
)

# ----------------------------------------------------------------------
zoom_in = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAHhJ"
    b"REFUSIntlUsOwCAIRKXp/a/c7roggwyI1SadnZ+8F8Foa3+cCLnvyjI8QQ9MsXqCCNzkWYIM"
    b"HDKPBDxUViQojRaMlAZyXj9BeU5n3Wooffs8AeqJGPMw3++BFrCPn5eHs6REo6cQc6Ay9TXN"
    b"SML/ASuquhib5gaFIQ4lGza61QAAAABJRU5ErkJggg=="
)

# ----------------------------------------------------------------------
zoom_out = PyEmbeddedImage(
    b"iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAG1J"
    b"REFUSIntlUsOABAMBRH3vzIbXYhPX1tdEG9LZtC0QvhhEsF9RcvgBDswxNoJJPAlbyXQwKfM"
    b"mcACH7jpAAwztZw4fcd2v4G7IDPraCNShifmBOaa3F+D9xqN4jqLLBJ4mmok4v8AFUmb8bJU"
    b"MBwNH31So2cAAAAASUVORK5CYII="
)
