"""empty message

Revision ID: f3c35e4b6b3a
Revises: 
Create Date: 2024-09-21 00:34:51.831112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c35e4b6b3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_note_tag_title', table_name='note_tag')
    op.drop_table('note_tag')
    op.drop_table('quotes_tags')
    op.drop_table('note')
    op.drop_index('ix_quote_tag_title', table_name='quote_tag')
    op.drop_table('quote_tag')
    op.drop_table('notes_tags')
    op.drop_table('quote')
    op.drop_table('bookmark')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('page_number', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('section_title', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('section_identifier', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('date_updated', sa.DATETIME(), nullable=True),
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('page_number', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('section_title', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('section_identifier', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('date_updated', sa.DATETIME(), nullable=True),
    sa.Column('start_pos', sa.INTEGER(), nullable=False),
    sa.Column('end_pos', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes_tags',
    sa.Column('note_id', sa.INTEGER(), nullable=True),
    sa.Column('note_tag_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['note_tag_id'], ['note_tag.id'], )
    )
    op.create_table('quote_tag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_tag_title', 'quote_tag', ['title'], unique=1)
    op.create_table('note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('page_number', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('section_title', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('section_identifier', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('date_updated', sa.DATETIME(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes_tags',
    sa.Column('quote_id', sa.INTEGER(), nullable=True),
    sa.Column('quote_tag_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ),
    sa.ForeignKeyConstraint(['quote_tag_id'], ['quote_tag.id'], )
    )
    op.create_table('note_tag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_note_tag_title', 'note_tag', ['title'], unique=1)
    # ### end Alembic commands ###
