on:
  push: {}

name: Build

env:
  PYTHONIOENCODING: utf-8

jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - name: Check out sources
        uses: actions/checkout@v3
      - name: Get Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: ${{ matrix.CI_ARCH }}
      - run: pip install invoke && invoke build && invoke create-portable
      - name: Upload portable
        uses: actions/upload-artifact@v3
        with:
          name: Bookworm-${{ matrix.CI_ARCH }}
          path: scripts/Bookworm*portable.zip
    strategy:
     matrix:
       CI_ARCH: ["x86", "x64"]
